'use client';

import { useActionState } from 'react';
import { Loader2 } from 'lucide-react';
import {
  updateCurriculumDocumentAction,
  type ActionResult,
} from '@/lib/admin-actions/program-curriculum';

const inputClass =
  'w-full rounded-lg border border-gray-300 px-3 py-2 text-sm font-mono focus:border-accent focus:outline-none focus:ring-2 focus:ring-accent/30';

export default function CurriculumDocumentForm({
  row,
}: {
  row: { id: string; pdfUrl: string | null; pdfFileName: string | null };
}) {
  const [state, action, pending] = useActionState(
    updateCurriculumDocumentAction.bind(null, row.id),
    { ok: null } as ActionResult | { ok: null },
  );

  return (
    <form action={action} className="space-y-4">
      <div>
        <label htmlFor="pdfUrl" className="mb-1 block text-xs font-medium text-gray-700">
          PDF URL
        </label>
        <input id="pdfUrl" name="pdfUrl" defaultValue={row.pdfUrl ?? ''} className={inputClass} />
        <p className="mt-1 text-xs text-gray-400">
          Generated by <code className="font-mono">scripts/build-curriculum-pdf.mjs</code> from the
          tables above, and named after a hash of its contents so a rebuilt file reaches people
          whose browser cached the old one.
        </p>
      </div>

      <div>
        <label htmlFor="pdfFileName" className="mb-1 block text-xs font-medium text-gray-700">
          Saved as
        </label>
        <input
          id="pdfFileName"
          name="pdfFileName"
          defaultValue={row.pdfFileName ?? ''}
          className={inputClass}
        />
      </div>

      <div className="flex items-center gap-3">
        <button
          type="submit"
          disabled={pending}
          className="inline-flex items-center gap-2 rounded-lg bg-primary px-4 py-2 text-sm font-medium text-white transition-colors hover:bg-primary/90 disabled:opacity-60"
        >
          {pending && <Loader2 size={15} className="animate-spin" />}
          Save
        </button>
        {state.ok === true && <span className="text-sm text-green-700">Saved</span>}
        {state.ok === false && <span className="text-sm text-red-600">{state.error}</span>}
      </div>
    </form>
  );
}
